/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.9 and Signal Processing Toolbox 8.5.
 * Generated on: 17-May-2023 13:08:36
 */

/*
 * 离散时间 IIR 滤波器(实数)
 * ----------------
 * 滤波器结构  : 直接 II 型，二阶节
 * 节数     : 2
 * 稳定     : 是
 * 线性相位   : 否
 */

/* General type conversion for MATLAB generated C-code  */
// #include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\MATLAB\R2020b\extern\include\tmwtypes.h 
 */
#define MWSPT_NSEC 5
const int NL[MWSPT_NSEC] = { 1,3,1,3,1 };
const double NUM[MWSPT_NSEC][3] = {
  {
   0.003759892814666,                 0,                 0 
  },
  {
                   1,                 0,                -1 
  },
  {
   0.003759892814666,                 0,                 0 
  },
  {
                   1,                 0,                -1 
  },
  {
                   1,                 0,                 0 
  }
};
const int DL[MWSPT_NSEC] = { 1,3,1,3,1 };
const double DEN[MWSPT_NSEC][3] = {
  {
                   1,                 0,                 0 
  },
  {
                   1,   -1.992790736958,   0.9929166195983 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,   -1.996420450107,   0.9964519767529 
  },
  {
                   1,                 0,                 0 
  }
};
